# Generated by Django 4.1 on 2022-09-16 16:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='<font color="red">*必填</font>', max_length=200)),
                ('text', models.TextField(help_text='<font color="red">*必填</font>')),
                ('area', models.IntegerField(choices=[(1, '基隆市'), (2, '台北市'), (3, '新北市'), (4, '桃園市'), (5, '新竹縣'), (6, '新竹市'), (7, '苗栗縣'), (8, '南投縣'), (9, '台中市'), (10, '彰化縣'), (11, '雲林縣'), (12, '嘉義縣'), (13, '嘉義市'), (14, '台南市'), (15, '高雄市'), (16, '屏東縣'), (17, '台東縣'), (18, '宜蘭縣'), (19, '花蓮縣'), (20, '澎湖縣'), (21, '金門縣'), (22, '連江縣')], default=1)),
                ('category', models.IntegerField(choices=[(1, '景點'), (2, '住宿'), (3, '餐廳')], default=1)),
                ('location', models.CharField(help_text='<font color="red">*必填</font>', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='類型是住宿或餐廳才要填', max_length=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('imgur_url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('stars', models.IntegerField(default=1, help_text='<font color="red">*必填</font>', max_length=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('lat', models.FloatField(default=1, help_text='<font color="red">*必填</font>')),
                ('lng', models.FloatField(default=1, help_text='<font color="red">*必填</font>')),
                ('visited', models.BooleanField(default=False, help_text='<font color="red">*必填</font>')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(default='#ff0000', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('imgur_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.tag')),
            ],
            options={
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, through='trips.Tag_post', to='trips.tag'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=150)),
                ('comment_man', models.CharField(default='訪客', max_length=25)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.post')),
            ],
            options={
                'db_table': 'post_comment',
                'ordering': ('-comment_date',),
            },
        ),
    ]
