# Generated by Django 4.1 on 2022-08-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.IntegerField(default=1, help_text='<font color="red">*必填</font>', max_length=1),
        ),
    ]
