# Generated by Django 4.1 on 2022-09-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag_post',
            options={'ordering': ('-post', 'order')},
        ),
        migrations.AddField(
            model_name='post',
            name='permanently_closed',
            field=models.BooleanField(default=False),
        ),
    ]
