# Generated by Django 4.1 on 2022-08-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_post_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgur_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
