# Generated by Django 4.1 on 2022-09-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_post_imgur_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(default=1, help_text='<font color="red">*必填</font>'),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.FloatField(default=1, help_text='<font color="red">*必填</font>'),
        ),
    ]
