# Generated by Django 4.1 on 2022-09-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tag_color_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
