# Generated by Django 4.1 on 2022-09-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_rename_tag_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
