# Generated by Django 4.1 on 2022-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
