# Generated by Django 4.1 on 2022-09-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_tag_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='svg',
        ),
        migrations.AddField(
            model_name='tag',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
