# Generated by Django 4.1 on 2022-09-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_remove_tag_svg_tag_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='imgur_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
